Repository LArSoft/larsoft, pull requests merged in 2020-02, with the labels that each got.

#4 Add two github actions to move new pull requests or issues to the LArSoft pull request project
  .github/workflows/opened-issues-triage.yml
  .github/workflows/opened-pulls-triage.yml
Labels: L1-approved, code-checks-approved, fully-signed, requires-external, tests-started

#3 Include hep_hpc in larsoft distribution.
  releaseDB/CMakeLists.txt
  releaseDB/lar_product_stack-cfg.in
  releaseDB/larbase-cfg.in
Labels: L1-approved, code-checks-approved, fully-signed, tests-started

#9 declare project language and update cmake_minimum_required
  CMakeLists.txt
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, requires-external, tests-started
